[package]
name = "jsonrpsee-client-transport"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "WebSocket client for JSON-RPC"
edition = "2021"
license = "MIT"
repository = "https://github.com/paritytech/jsonrpsee"
homepage = "https://github.com/paritytech/jsonrpsee"
documentation = "https://docs.rs/jsonrpsee-ws-client"

[dependencies]
jsonrpsee-types = { path = "../../types", version = "0.9.0", optional = true }
jsonrpsee-core = { path = "../../core", version = "0.9.0", features = ["client"] }
tracing = "0.1"
thiserror = { version = "1", optional = true }
futures-channel = { version = "0.3.14", default-features = false, optional = true }
futures-util = { version = "0.3.14", default-features = false, optional = true }
http = { version = "0.2", optional = true }
tokio-util = { version = "0.6", features = ["compat"], optional = true }
tokio = { version = "1", features = ["net", "time", "macros"], optional = true }
pin-project = { version = "1", optional = true }
rustls-native-certs = { version = "0.6", optional = true }
webpki-roots = { version = "0.22", optional = true }
tokio-rustls = { version = "0.23", optional = true }

# ws
soketto = { version = "0.7.1", optional = true }

# wasm
wasm-bindgen = { version = "0.2.69", optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
js-sys = { version = "0.3.46", optional = true }
web-sys = { version = "0.3.46", features = ["BinaryType", "Blob", "ErrorEvent", "FileReader", "MessageEvent", "CloseEvent", "ProgressEvent", "WebSocket", "console"], optional = true }

[features]
tls = ["tokio-rustls", "webpki-roots", "rustls-native-certs"]
ws = [
    "futures-util",
    "http",
    "tokio",
    "tokio-util",
    "soketto",
    "pin-project",
    "jsonrpsee-types",
    "thiserror",
]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "js-sys", "web-sys", "futures-channel", "futures-util"]
