[workspace]
members = [
	"examples",
	"benches",
	"http-server",
	"test-utils",
	"jsonrpsee",
	"tests",
	"types",
	"core",
	"ws-server",
	"client/ws-client",
	"client/http-client",
	"client/transport",
	"proc-macros",
]
exclude = ["wasm-tests"]
resolver = "2"
