[package]
name = "jsonrpsee-core"
version = "0.8.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Utilities for jsonrpsee"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
arrayvec = "0.7.1"
async-trait = "0.1"
async-channel = { version = "1.6", optional = true }
beef = { version = "0.5.1", features = ["impl_serde"] }
snafu = { version = "0.7", default-features = false }
futures-channel = { version = "0.3.14", default-features = false }
futures-util = { version = "0.3.14", default-features = false, optional = true }
hyper = { version = "0.14.10", default-features = false, features = ["stream"], optional = true }
jsonrpsee-types = { path = "../types", version = "0.8.0" }
tracing = { version = "0.1", optional = true }
rustc-hash = { version = "1", default-features = false, optional = true }
hashbrown = { version = "0.12", optional = true }
rand = { version = "0.8", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
soketto = { version = "0.7.1", optional = true }
parking_lot = { version = "0.12", optional = true }
tokio = { version = "1.8", features = ["rt"], optional = true }
wasm-bindgen-futures = { version = "0.4.19", optional = true }

[features]
default = []
http-helpers = ["hyper", "futures-util"]
server = [
	"async-channel",
	"futures-util",
	"rustc-hash/std",
	"tracing",
	"parking_lot",
	"rand",
	"tokio",
	"soketto",
	"snafu/std",
]
client = ["futures-util/sink", "futures-channel/sink", "futures-channel/std"]
async-client = [
	"client",
	"rustc-hash",
	"hashbrown",
	"tokio/sync",
	"tokio/macros",
	"tokio/time",
	"tracing",
	"snafu/std"
]
async-client-wasm = [
	"client",
	"wasm-bindgen-futures",
	"hashbrown",
	"rustc-hash",
]

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1.8", features = ["macros", "rt"] }
jsonrpsee = { path = "../jsonrpsee", features = ["server", "macros"] }
