name: Continuous integration

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  # Use latest substrate for nightly runs:
  SUBSTRATE_URL: https://releases.parity.io/substrate/x86_64-debian:stretch/latest/substrate/substrate

jobs:
  check-style:
    name: Check style
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.4.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo fmt
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1.0.3
        with:
          command: clippy
          args: --all-targets

      - name: Check rustdoc links
        run: RUSTDOCFLAGS="--deny broken_intra_doc_links" cargo doc --verbose --workspace --no-deps --document-private-items

  check-code:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.4.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo check all targets and features
        run: cargo hack check --workspace --each-feature --all-targets

  tests:
    name: Run tests Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --workspace

  tests_macos:
    name: Run tests macos
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --workspace

  tests_windows:
    name: Run tests Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Cargo test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --workspace

  test_wasm:
    name: Test wasm
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Download Substrate
      run: |
        curl $SUBSTRATE_URL --output substrate --location
        chmod +x substrate
        mkdir -p ~/.local/bin
        mv substrate ~/.local/bin

    - name: Run WASM tests
      run: |
        substrate --dev --tmp > /dev/null 2>&1 &
        wasm-pack test --headless --firefox
        wasm-pack test --headless --chrome
        pkill substrate
      working-directory: wasm-tests
